require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Use S3 when S3_BUCKET is set to a real bucket; otherwise local disk (see config/storage.yml).
  config.active_storage.service = if ENV["S3_BUCKET"].present? && ENV["S3_BUCKET"] != "unused"
    :amazon
  else
    :local
  end

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Disable digesting assets with an md5 tag.
  config.assets.digest = false

  # Propshaft uses public/assets/.manifest.json when it exists (e.g. after
  # `rails assets:precompile`). That static manifest omits gem-only assets such as
  # hotwire_spark.js, which breaks Hotwire Spark and other engine scripts in dev.
  # Point at a path that does not exist so Propshaft resolves assets dynamically.
  config.assets.manifest_path = Rails.root.join("tmp", "propshaft-development.manifest.json")

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Comma separated list of IP addresses / CIDRs that can use the web-console
  # which is invoked with `console` in a controller or <% console %> in a view.
  #
  # Docker supports a bunch of ranges so let's just support everything. This
  # isn't insecure due to only running in development.
  config.web_console.allowed_ips = [ "0.0.0.0/0" ]
end
